#!/bin/bash -e

# ensure that we have the required dependencies installed
for dep in aspell pylint; do
    if ! type -t $dep > /dev/null; then
        echo "Error: '$dep' is not installed" 1>&2
        exit 1
    fi
done

# run the adoc spell checker over all the available AsciiDoc files, this should reduce wasted time when there's trivial
# spelling mistakes.
./jenkins/adoc-lint.sh

# run multiple linters over the codebase before allowing allowing a push (these are the same linters that the build bot
# runs), therefore, this should mean less wasted time spent fixing mistakes picked up when it's least convenient to fix
# them.
pylint --errors-only --disable=import-error cblogredaction cbrecovery cbtransfer cbworkloadgen couchbase-cli pump*.py
pylint --errors-only --disable=import-error,unused-import --disable C,R cbmgr.py cluster_manager.py
