= couchbase-cli-reset-admin-password(1)
ifndef::doctype-manpage[:doctitle: reset-admin-password]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-reset-admin-password -
endif::[]
Resets the Couchbase Server administrator password

== SYNOPSIS

[verse]
_couchbase-cli reset-admin-password_ [--regenerate] [--new-password <password>]
    [--port <port>]

== DESCRIPTION

This command is used to reset the built-in Couchbase Server Administrator
password. There is only one built-in Administrator account, which is managed
separately from the internal and external Administrator users. External and
internal Administrator accounts can be managed using the
man:couchbase-cli-user-manage[1] command.

The `reset-admin-password` command must be run locally on a node that is part
of the cluster (i.e. must connect to the host the command is run on). This is
required, as `reset-admin-password` relies on a local authentication token,
which is used to authenticate with the server and change the password. As a
result, the command does not require credentials to be passed.

== OPTIONS

--new-password <password>::
  Sets the password for the Couchbase Server administrator user to the value
  specified by the argument. If no password is specified, the command
  prompts the user for the new password through non-echoed stdin.

--regenerate::
  Sets the password for the Couchbase Server administrator user to a randomly
  generated value. The new password is printed to the command line after
  the password is changed.

--port::
  Specify the REST API port of the locally running Couchbase Server. If no
  port is specified the default port 8091 is used.

== EXAMPLES

To change the administrator password to `new_pwd`, run the following command:
----
  $ couchbase-cli reset-admin-password --new-password new_pwd
----

To change the administrator password to a randomly generated value, run the
following command. The new password will be printed to stdout if the
password is successfully changed:
----
$ couchbase-cli reset-admin-password --regenerate jXjNW6LG
----
== SEE ALSO

man:couchbase-cli-setting-ldap[1],
man:couchbase-cli-user-manage[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
