= couchbase-cli-setting-autofailover(1)
ifndef::doctype-manpage[:doctitle: setting-autofailover]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-setting-autofailover -
endif::[]
Modifies auto-failover settings

== SYNOPSIS

[verse]
_couchbase-cli setting-autofailover_ [--cluster <url>] [--username <user>]
    [--password <password>] [--enable-auto-failover <num>]
    [--auto-failover-timeout <seconds>]
    [--enable-failover-on-data-disk-issues <num>]
    [--failover-data-disk-period <seconds>] [--can-abort-rebalance <1|0>]

== DESCRIPTION

Auto-failover allows unresponsive servers to be failed over automatically by the
cluster manager. Data partitions in Couchbase are always served from a single
master node. As a result if a server is down in the cluster data from that
server will be not be available while that server is down. The server will
either need to be manually or automatically failed over in order to promote
replica data partitions on replica servers to active data partitions so that
they can be accessed by the application.

Since the administrator will not always be able to manually fail servers over
quickly enough to avoid application down time Couchbase provides an
auto-failover feature. This feature allows the cluster manager to automatically
fail over down nodes over and bring the cluster back to a healthy state as
quickly as possible.

In Couchbase Server Enterprise Edition nodes can also be automatically failed
over when the Data Service reports sustained disk I/O failures.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--enable-auto-failover <num>::
  Specifies whether or not autofailover is enabled. Set this option to "1" to
  enable autofailover or "0" to disable autofailover.

--auto-failover-timeout <seconds>::
  Specifies the auto-failover timeout. This is the amount of time a node must
  be unresponsive before the cluster manager considers the node to be down and
  fails it over. The minimum auto-failover timeout is 30 seconds in Couchbase
  Community Edition and 5 seconds in Couchbase Enterprise Edition.

--max-failovers <num>::
  Specifies the number of auto-failover events that will be handled before
  requiring user intervention. A single event could be one node failing over or
  an entire Server Group. The maximum allowed value is three. This feature is
  only available in Couchbase Enterprise Edition.

--enable-failover-of-server-groups <num>::
  Specifies whether or not auto-failover can failover entire Server Groups.
  This feature is only available in Couchbase Enterprise Edition.

--enable-failover-on-data-disk-issues <num>::
  Specifies whether or not autofailover on Data Service disk issues is enabled.
  Set this option to "1" to enable failover on Data Service disk issue or
  "0" to disable it. "--failover-data-disk-period" needs to be set at the
  same time when enabling this option. This feature is only available in
  Couchbase Enterprise Edition.

--failover-data-disk-period <seconds>::
  Specifies the failover data disk period. This is the period of time over
  which the Data Service is checked for potential sustained Disk I/O
  failures. The Data Service is checked every second for disk failures. If
  60% of the checks during that time period report disk failures, then the
  node may be automatically failed over.
  "--enable-failover-on-data-disk-issues" must be set when this option is
  used. The failover data disk period ranges from 5 to 3600 seconds.

--can-abort-rebalance <1|0>::
  Enables auto-failover to abort rebalance and perform auto-failover.
  This feature is only available in Couchbase Enterprise Edition.

include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

To enable autofailover with a 30 second auto-failover timeout run the following
command.

  $ couchbase-cli setting-autofailover -c 192.168.1.5 --username Administrator \
   --password password --enable-auto-failover 1 --auto-failover-timeout 30

To enable autofailover with a 120 second auto-failover timeout run the following
command.

  $ couchbase-cli setting-autofailover -c 192.168.1.5 --username Administrator \
   --password password --enable-auto-failover 1 --auto-failover-timeout 120

To enable autofailover with a 120 second auto-failover timeout and to enable
failover on Data Service Disk issue with a 10 second data disk period run the
following command.

  $ couchbase-cli setting-autofailover -c 192.168.1.5 --username Administrator \
   --password password --enable-auto-failover 1 --auto-failover-timeout 120 \
   --enable-failover-on-data-disk-issues 1 --failover-data-disk-period 10

To enable autofail with a 120 second auto-failover timeout and to enable failover
of a Server group and allow up to two auto failover event

  $ couchbase-cli setting-autofailover -c 192.168.1.5 --username Administrator \
   --password password --enable-auto-failover 1 --auto-failover-timeout 120 \
   --enable-failover-of-server-groups 1 --max-failovers 2

To disable autofailover run the following command.

  $ couchbase-cli setting-autofailover -c 192.168.1.5 --username Administrator \
   --password password --enable-auto-failover 0

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-failover[1],
man:couchbase-cli-recovery[1],
man:couchbase-cli-setting-alert[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
