= couchbase-cli-setting-enterprise-analytics(1)
:description: Manage Operational Insights service settings (deprecated)
ifndef::doctype-manpage[:doctitle: setting-enterprise-analytics]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-setting-enterprise-analytics -
endif::[]
Manage Operational Insights service settings (deprecated)

== SYNOPSIS

[verse]
_couchbase-cli setting-enterprise-analytics_ [<options>]

== DESCRIPTION

DEPRECATED: Please use the man:couchbase-cli-setting-operational-insights[1]
command, which provides the same functionality as this command and takes the
same options. This command is retained only so that scripts written against
the former product name keep working, and it will be removed in a future
release.

This command addresses the cluster through the REST endpoint of the former
product name, so it remains usable against a cluster which is older than the
`setting-operational-insights` command.

== OPTIONS

See man:couchbase-cli-setting-operational-insights[1].

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-setting-operational-insights[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
