= couchbase-cli-admin-manage(1)
:description: Manages the built-in Couchbase Server administrator
ifndef::doctype-manpage[:doctitle: admin-manage]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-admin-manage -
endif::[]
Manages the built-in Couchbase Server administrator

== SYNOPSIS

[verse]
_couchbase-cli admin-manage_ [--ip <ip>] [--port <port>] --lock | --unlock

== DESCRIPTION

This command is used to manage the built-in Couchbase Server Administrator user.
There is only one built-in Administrator account, which is managed separately
from the internal and external Administrator users. External and internal
Administrator accounts can be managed using the
man:couchbase-cli-user-manage[1] command.

The `admin-manage` command must be run locally on a node that is part of the
cluster (i.e. must connect to the host the command is run on). This is required,
as `admin-manage` relies on a local authentication token, which is used to
authenticate with the server and perform actions such as locking the user. As a
result, the command does not require credentials to be passed.

== OPTIONS
--port::
  Specify the REST API port of the locally running Couchbase Server. If no
  port is specified the default port 8091 is used.

--ip::
  Specify the IP address of the locally running Couchbase Server. If no
  ip is specified the default ip localhost is used.

--lock::
  Locks the built-in administrator user.

--unlock::
  Unlocks the built-in administrator user.

== EXAMPLES

To lock the built-in administrator, run the following command:
----
  $ couchbase-cli admin-manage --lock
----

To unlock the built-in administrator, run the following command:
----
  $ couchbase-cli admin-manage --unlock
----

== SEE ALSO

man:couchbase-cli-user-manage[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
