= couchbase-cli-enterprise-analytics-link-setup(1)
:description: Manage Operational Insights links (deprecated)
ifndef::doctype-manpage[:doctitle: enterprise-analytics-link-setup]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-enterprise-analytics-link-setup -
endif::[]
Manage Operational Insights links (deprecated)

== SYNOPSIS

[verse]
_couchbase-cli enterprise-analytics-link-setup_ [<options>]

== DESCRIPTION

DEPRECATED: Please use the man:couchbase-cli-operational-insights-link-setup[1]
command, which provides the same functionality as this command and takes the
same options. This command is retained only so that scripts written against
the former product name keep working, and it will be removed in a future
release.

== OPTIONS

See man:couchbase-cli-operational-insights-link-setup[1].

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-operational-insights-link-setup[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
