= couchbase-cli-change-cluster-encryption(1)
ifndef::doctype-manpage[:doctitle: change-cluster-encryption]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-change-cluster-encryption -
endif::[]
Changes cluster encryption

== SYNOPSIS

[verse]
_couchbase-cli change-cluster-encryption_ [--cluster <url>] [-username <username>]
    [--password <password>] [--get] [--enable] [--disable]

== DESCRIPTION

This command allows the enabling and disabling of cluster encryption this means
data transferred between nodes in a cluster will be encrypted. The command will
execute a series of instructions in each node in the cluster to switch them
from sending and receiving over a non-encrypted connection to an encrypted one
or vice-versa.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--get::
  Display the cluster encryption setting

--enable::
  Will enable cluster encryption

--disable::
  Will disable cluster encryption

include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

To enable cluster encryption in a cluster with two host
`[cb1.mydomain.com:8091, cb2.mydomain.com:8091]` ran the following
commands:

  $ couchbase-cli change-cluster-encryption -c cb1.mydomain.com:8091 --username Administrator \
   --password password --enable


To check if cluster encryption is on or off ran:

 $ couchbase-cli change-cluster-encryption -c cb1.mydomain.com:8091 --username Administrator \
   --password password --get

To disable cluster encryption use the following command:

   $ couchbase-cli change-cluster-encryption -c cb1.mydomain.com:8091 --username Administrator \
   --password password --disable


== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-setting-security[1]
man:couchbase-ssl-manage[1]
man:couchbase-cli-change-ip-family[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
