= couchbase-cli-operational-insights-link-setup(1)
:description: Manage Operational Insights links
ifndef::doctype-manpage[:doctitle: operational-insights-link-setup]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-operational-insights-link-setup -
endif::[]
Manage Operational Insights links

== SYNOPSIS

[verse]
_couchbase-cli operational-insights-link-setup_ [--cluster <cluster>] [--username <username>]
    [--password <password>] [--client-cert <path>] [--client-cert-password <password>]
    [--client-key <path>] [--client-key-password <password>] [--create] [--delete]
    [--edit] [--get] [--list] [--name <name>] [--type <type>] [--link-details <json>]
    [--link-details-path <path>]

== DESCRIPTION

This command is used to manage links used by the external dataset and remote
cluster capabilities of the Operational Insights Service.

== OPTIONS

=== Common Link Options

include::{partialsdir}/cbcli/part-common-options.adoc[]

--create::
  Creates a new link.

--delete::
  Deletes a link.

--edit::
  Edits a link.

--get::
  Retrieve link details.

--list::
  List defined links.

--name <name>::
  The name of the link.

--type <type>::
  Only list links of the given type, for example `s3`, `azureblob`, `azuredatalake`,
  `gcs` or `kafka`. May only be used with `--list`.

--link-details <json>::
  The link details as JSON string

--link-details-path <path>::
  The path to the link details JSON file

include::{partialsdir}/cbcli/part-host-formats.adoc[]

include::{partialsdir}/cbcli/part-certificate-authentication.adoc[]

== EXAMPLES

To create a new link named "l1", run the following command:

$ couchbase-cli operational-insights-link-setup -c 192.168.1.5 -u Administrator \
 -p password --create --name l1 --link-details-path <path>

To delete the new link named "l1", run the following command:

$ couchbase-cli operational-insights-link-setup -c 192.168.1.5 -u Administrator \
 -p password --delete --name l1

To list the defined links run the following command:

$ couchbase-cli operational-insights-link-setup -c 192.168.1.5 -u Administrator \
 -p password --list

To list only the defined S3 links, run the following command:

$ couchbase-cli operational-insights-link-setup -c 192.168.1.5 -u Administrator \
 -p password --list --type s3

To retrieve the link details for a link named "l1", run the following command:

$ couchbase-cli operational-insights-link-setup -c 192.168.1.5 -u Administrator \
 -p password --get --name l1

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

include::{partialsdir}/cbcli/part-footer.adoc[]
