= couchbase-cli-setting-encryption(1)
:description: Manage encryption at-rest settings.
ifndef::doctype-manpage[:doctitle: setting-encryption]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-setting-encryption -
endif::[]
Manage encryption at-rest settings.

== SYNOPSIS

[verse]
_couchbase-cli setting-enable_ [--cluster <url>] [--username <user>]
    [--password <password>] [--client-cert <path>] [--client-cert-password <password>]
    [--client-key <path>] [--client-key-password <password>]
    [--get] [--set] [--list-keys]
    [--target <target>] [--type <type>] [--key <keyid>]
    [--dek-rotate-every <days>] [--dek-lifetime <days>]

== DESCRIPTION

Allows managing encryption at-rest settings, including create/editing/rotating/deleting
keys and choosing what encryption to use for config, logs and audit logs.

The operation the command performs is determined by several mutually exclusive
arguments, each having their own set of options:

* `--get`
* `--set`, with the args
  ** `--target <target>`, `--type <type>`, `--key <keyid>`,
     `--dek-rotate-every <days>`, `--dek-lifetime <days>`
* `--list-keys`

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--get::
  Gets the encryption settings for configuration, logs and audit logs.

--set::
  Sets the encryption settings. `--target` and `--type` must be specified.

--target <target>::
  Used with `--set` to determine what encryption settings are being changed.
  Can be `config`, `log` or `audit`.

--type <type>::
  The type of encryption to use. Can be `disabled`, `key` or `master-password`.

--key <keyid>::
  The id of the key to use. Should only be passed if `--type` is `key`.

--dek-rotate-every <days>::
  How often to rotate the DEK.

--dek-lifetime <days>::
  How long the DEKs should be kept for.

--list-keys::
  List the keys and their settings in JSON format.

== EXAMPLES
To list the available encryption keys run the following command

  $ couchbase-cli setting-encryption -c 192.168.1.5 -u Administrator \
   -p password --list-keys

To get the settings for configuration, logs and audit log encryption

  $ couchbase-cli setting-encryption -c 192.168.1.5 -u Administrator \
   -p password --get

To set the configuration settings to be encrypted with the key with the id 2

  $ couchbase-cli setting-encryption -c 192.168.1.5 -u Administrator \
   -p password --set --target config --type key --key 2

To encrypt audit logs with the master password, rotating the data encryption key
(DEK) every thirty days and keeping the DEKs for sixty days:

  $ couchbase-cli setting-encryption -c 192.168.1.5 -u Administrator \
   -p password --set --target config --type master-password \
   --dek-rotate-every 30 --dek-lifetime 60

To disable encryption for logs

  $ couchbase-cli setting-encryption -c 192.168.1.5 -u Administrator \
   -p password --set --target log --type disabled

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

include::{partialsdir}/cbcli/part-footer.adoc[]
