= couchbase-cli-settings-alternate-address(1)
:description: Modify alternate addresses
ifndef::doctype-manpage[:doctitle: setting-alternate-address]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-setting-alternate-address -
endif::[]
Modify alternate addresses

== SYNOPSIS

[verse]
_couchbase-cli setting-alternate-address_ [--cluster <url>] [--username <user>]
    [--password <password>] [--list] [--set] [--remove] [--hostname <host>]
    [--ports <ports>]

== DESCRIPTION

This command is used to set the alternate address for a node. This alternate address
allows the node to be connected by a different address, this is useful when an external
agent tries to connect via a NAT'd environment such as the cloud or kubernetes.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--list::
  Show current alternate addresses. Please note only the first 43 characters hostname and
  alternate address are displayed. The full hostnames are shown in the json output
  (-o json).

--set::
  Set alternate address for the node specified in the -c/--cluster option.

--remove::
  Remove alternate address for the node specified in the -c/--cluster option.

--node <node>::
  The node in the cluster to take action on. This is required when using
  --set or --remove flags.

--hostname <host>::
  Alternate host address

--ports <port>::
  Alternate port mappings. Specified as a comma separated list:
 e.g. `--ports kv=9000,kvSSL=9999.`

include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

To set the alternate address and custom ports for node 192.168.1.5 we would use the
following command:
----
$ couchbase-cli setting-alternate-address -c 192.168.1.5:8091 --username Administrator \
   --password password --set --node 192.168.1.5 --hostname 10.10.10.10 \
   --ports mgmt=1100,capi=2000,capiSSL=3000
----
To see the current alternate address configuration we would use the --list flag as
follows:
----
$ couchbase-cli setting-alternate-address -c 192.168.1.5:8091 --username Administrator \
   --password password --list
----
== DISCUSSION

All of the ports that can be configured:

.Alternate Ports
|===
|Port Name | Encrypted Port Name | Service | Description

|`mgmt`
|`mgmtSSL`
|Cluster Manager
|The UI and REST API for managing the Cluster

|`kv`
|`kvSSL`
|Data
|Used by the SDKs and XDCR to transfer data to and from the Data Service

|`capi`
|`capiSSL`
|View Engine
|Used by the SDKs and XDCR

|`n1ql`
|`n1qlSSL`
|Query
|Used by the SDKs to query data

|`fts`
|`ftsSSL`
|Search
|Used by the SDKs to do full text searches

|`cbas`
|`cbasSSL`
|Analytics
|Used by the SDKs to query data managed by the Analytic service

|`eventingAdminPort`
|`eventingSSL`
|Eventing
|Used by the SDK to transfer data to and from the Eventing Service

|`eventingDebug`
|N/A
|Eventing
|The Eventing debugger port, this should only be set in development environments.

|`backupAPI`
|`backupAPIHTTPS`
|Backup
|The backup service REST API.

| N/A
|`backupGRPC`
|Backup
|Used by backup nodes to communicate with each other.

|===


== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-cluster-init[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
