= couchbase-cli-bucket-list(1)
ifndef::doctype-manpage[:doctitle: bucket-list]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-bucket-list -
endif::[]
List all buckets

== SYNOPSIS

[verse]
_couchbase-cli bucket-list_ [--cluster <url>] [--username <user>]
    [--password <password>]

== DESCRIPTION

Lists all buckets in the cluster. For each bucket, the following are printed
to stdout: `bucketType`, `authType`, `numReplicas`, `ramQuota`, `ramUsed`.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

To list all buckets in the cluster, run the following command.
----
$ couchbase-cli bucket-list -c 192.168.1.5:8091 --username Administrator \
 --password password

 travel-data
   bucketType: membase
   authType: sasl
   numReplicas: 1
   ramQuota: 104857600
   ramUsed: 45302840
 airline-data
   bucketType: ephemeral
   authType: sasl
   numReplicas: 1
   ramQuota: 268435456
   ramUsed: 1134432
 flight-data
   bucketType: memcached
   authType: sasl
   numReplicas: 0
   ramQuota: 104857600
   ramUsed: 0
----
== DISCUSSION

In the output, RAM figures are in bytes. The "membase" bucketType signifies a
Couchbase bucket. The authType can be either "sasl" or "none".

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-bucket-compact[1],
man:couchbase-cli-bucket-create[1],
man:couchbase-cli-bucket-delete[1],
man:couchbase-cli-bucket-edit[1],
man:couchbase-cli-bucket-flush[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
