= couchbase-cli-backup-service-repo-worm(1)
:description: Configure WORM for a backup service repository
ifndef::doctype-manpage[:doctitle: backup-service repo-worm]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-backup-service-repo-worm -
endif::[]
Configure WORM for a backup service repository

== SYNOPSIS

[verse]
_couchbase-cli backup-service_ [--cluster <url>] [--username <user>]
    [--password <password>] [--client-cert <path>]
    [--client-cert-password <password>] [--client-key <path>]
    [--client-key-password <password>] _repo-worm_ [--id <id>]
    (--period <days> | --disable)

== DESCRIPTION

Configures Write Once Read Many (WORM) compliance settings for a backup service
repository. WORM ensures that backup data cannot be modified or deleted for a
specified retention period, providing data immutability for regulatory compliance.

This command allows you to either set a WORM compliance period (in days) or
disable WORM for a repository once its validity period has expired. Only paused
repositories can have their WORM configuration modified.

== OPTIONS

--id <id>::
    The repository ID. This argument is required.

--period <days>::
    The WORM compliance period in days. Valid values are between 3 and 36525
    days (approximately 100 years). This option is mutually exclusive with
    `--disable`.

--disable::
    Disable WORM for the repository once its validity period has expired. This
    option is mutually exclusive with `--period`.

include::{partialsdir}/cbcli/part-common-options.adoc[]

include::{partialsdir}/cbcli/part-host-formats.adoc[]

include::{partialsdir}/cbcli/part-certificate-authentication.adoc[]

== EXAMPLES

To set a WORM compliance period of 30 days for a repository named 'weekly-backup',
run the following command.

----
$ couchbase-cli backup-service -c 127.0.0.1:8091 -u Administrator -p password \
  repo-worm --id weekly-backup --period 30
----

If successful, the following output will be displayed:

----
Repository WORM config was set
----

To set a WORM compliance period of 3 days:

----
$ couchbase-cli backup-service -c 127.0.0.1:8091 -u Administrator -p password \
  repo-worm --id my-repo --period 3
----

To disable WORM for a repository after its validity period has expired:

----
$ couchbase-cli backup-service -c 127.0.0.1:8091 -u Administrator -p password \
  repo-worm --id old-backup --disable
----

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-backup-service[1],
man:couchbase-cli-backup-service-repo-list[1],
man:couchbase-cli-backup-service-repo-get[1],
man:couchbase-cli-backup-service-repo-add[1],
man:couchbase-cli-backup-service-repo-archive[1]

include::{partialsdir}/cbcli/part-footer.adoc[]

