= couchbase-cli-reset-admin-password(1)
ifndef::doctype-manpage[:doctitle: reset-admin-password]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-reset-admin-password -
endif::[]
Resets the Couchbase Server administrator password

== SYNOPSIS

[verse]
_couchbase-cli reset-admin-password_ [--cluster <url>] [--regenerate]
    [--new-password <password>]

== DESCRIPTION

This command is used to reset the built-in Couchbase Server Administrator password.
There is only one built-in Administrator account, which is managed separately
from the internal and external Administrator users.
External and Internal Administrator
accounts can be managed using the man:couchbase-cli-user-manage[1] command.

The `reset-admin-password` command must be run locally on a node that is part of the
cluster (i.e. must connect to the host the command is run on).
This is required as `reset-admin-password`
relies on a local authentication token, which is used to authenticate with the
server and change the password. As a result, the command does not require
credentials to be passed.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options-no-creds.adoc[]

--new-password <password>::
  Sets the password for the Couchbase Server administrator user to the value
        specified by the argument. If no password is
  specified, the command prompts the user for the new
  password through non-echoed stdin.

--regenerate::
  Sets the password for the Couchbase Server administrator user to a randomly
  generated value. The new password is printed to the command line after
  the password is changed.

include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

To change the administrator password to _new_pwd_ run the following command:

  $ couchbase-cli reset-admin-password -c 192.168.1.5:8091 \
   --new-password new_pwd

To change the administrator password to a randomly generated value, run the
following command. The new password will be printed to stdout if the
password is successfully changed:

  $ couchbase-cli reset-admin-password -c 192.168.1.5:8091 --regenerate
    jXjNW6LG

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-setting-ldap[1],
man:couchbase-cli-user-manage[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
