= couchbase-cli-setting-query(1)
:description: Manage query engine settings
ifndef::doctype-manpage[:doctitle: setting-query]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-setting-query -
endif::[]
Manage query engine settings

== SYNOPSIS

[verse]
_couchbase-cli setting-query [--cluster <url>] [--username <user>] [--password <password>]
    [--client-cert <path>] [--client-cert-password <password>] [--client-key <path>]
    [--client-key-password <password>] [--get] [--set] [--pipeline-batch <num>]
    [--pipeline-cap <num>] [--scan-cap <size>] [--timeout <ms>]
    [--prepared-limit <max>] [--completed-limit <max>]
    [--log-level <trace|debug|info|warn|error|server|none>]
    [--max-parallelism <max>] [--n1ql-feature-control <num>]
    [--temp-dir <path>] [--temp-dir-size <mebibytes>]
    [--cost-based-optimizer <1|0>] [--memory-quota <mebibytes>]
    [--transaction-timeout <duration>] [--node-quota <mebibytes>]
    [--node-quota-val-percent <perc>] [--use-replica <unset|off|on>]
    [--curl-access <restricted|unrestricted>] [--allowed-urls <urls>]
    [--disallowed-urls <urls>]

== DESCRIPTION

Manage query service settings

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--get::
  Retrieve current query service settings.

--set::
  Set query engine settings.

--pipeline-batch <num>::
  Number of items execution operators can batch, the default is 16.

--pipeline-cap <num>::
  Maximum number of items each execution operator can buffer, the default 512.

--scan-cap <size>::
  Maximum buffer size for index scans; use zero or negative value to disable.
  The default 512.

--timeout <ms>::
  Server execution timeout; use zero or negative value to disable. By default
  is unlimited.

--prepared-limit <max>::
  Maximum number of prepared statements, the default is 16384.

--completed-limit <max>::
  Maximum number of completed requests, the default is 4000.

--completed-threshold <ms>::
  Cache completed queries lasting longer than this threshold (in milliseconds),
  the default is 1000.

--log-level <trace|debug|info|warn|error|server|none>::
  Query engine log level, the default level is info.

--max-parallelism <max>::
  Maximum parallelism per query; use zero or negative value to disable.
  The default is 1.

--n1ql-feature-control <num>::
  {sqlpp} Feature Controls.
  0x0001 (1) Disable Index Aggregation

--temp-dir <path>::
  Specify the directory for temporary query data.

--temp-dir-size <mebibytes>::
  Maximum size in mebibytes for the temporary query data directory.

--cost-based-optimizer <1|0>::
  Enable (1) or disable (0) the Cost Based Optimizer (CBO), which uses
  statistics and metadata to estimate the amount of processing required
  and creates a query plan with the least cost. This feature is in
  Developer Preview and should not be used in production environments.

--memory-quota <mebibytes>::
  The maximum amount of memory the query service will use in each node.

--transaction-timeout <duration>::
  The timeout for transactional queries. The duration is a number followed
  by a unit such as (100ns, 10ms, 1s, 1m).

--node-quota <mebibytes>::
  The maximum amount of memory that the query service will allow node wide for
  loaded documents, not including caches, plans or transactions.

--node-quota-val-percent <perc>::
  The percentage of node-quota that is reserved for value memory.

--use-replica <unset|off|on>::
  Specify whether or not a query can read from replica vBuckets. When set to
  "unset", whether or not replica vBuckets are read from is set at request
  level. When set to "off", it is always disabled for all queries and this
  cannot be overridden. When set to "on", it is by default enabled for all
  queries, but this can be disabled at request level.

== QUERY CURL ACCESS OPTIONS

--curl-access <restricted|unrestricted>::
  Specify either unrestricted or restricted, to determine which URLs are permitted
  to be accessed by the curl function.

--allowed-urls <urls>::
  Comma separated lists of URLs that are allowed to be accessed by the curl
  function. This option must be provided together with --curl-access restricted.
  If disallowed-urls also provided then the disallowed list takes precedence.

--disallowed-urls <urls>::
  Comma separated lists of URLs that are disallowed to be accessed by the curl
  function. This option must be provided together with --curl-access restricted.
  If allowed-urls also provided then the disallowed list takes precedence.

include::{partialsdir}/cbcli/part-host-formats.adoc[]

include::{partialsdir}/cbcli/part-certificate-authentication.adoc[]

== EXAMPLES

To retrieve the query settings:

  $ couchbase-cli setting-query -c 127.0.01:8091 -u Administrator \
   -p password --get

To set any of the query settings for example maximum parallelism and log level:

  $ couchbase-cli setting-query -c 127.0.01:8091 -u Administrator \
   -p password --set --log-level debug --max-parallelism 4

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
