= couchbase-cli-collection-manage(1)
:description: Manage collections and scopes in a bucket
ifndef::doctype-manpage[:doctitle: collection-manage]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-collection-manage -
endif::[]
Manage collections and scopes in a bucket

== SYNOPSIS

[verse]
_couchbase-cli collection-manage_ [--cluster <url>] [--username <user>]
    [--password <password>] [--client-cert <path>] [--client-cert-password <password>]
    [--client-key <path>] [--client-key-password <password>] [--bucket <bucket>]
    [--create-scope <scope>] [--drop-scope <scope>] [--list-scopes]
    [--create-collection <collection>] [--edit-collection <collection>]
    [--drop-collection <collection>] [--list-collections [<scope_list>]]
    [--max-ttl <seconds>] [--enable-history-retention <0|1>]

== DESCRIPTION

This command is used to manage collections and scopes in a bucket.
Collections allow the user to categorize the data in the bucket
by creating collections and specifying a collection when adding
documents to a bucket. Scopes are the grouping of collections,
which allows further categorization and ease of management.

The following rules define a valid collection or scope name:

* Must be between 1 and 30 bytes long
* Can only contain characters A-Z, a-z, 0-9 and the following
symbols _ - %
* Cannot start with _ or %

Only Couchbase and Ephemeral bucket has Collection support.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--bucket <bucket>::
  The name of the bucket.

--create-scope <scope>::
  Makes a scope in the bucket with the name provided.

--drop-scope <scope>::
  Removes the scope from the bucket with the name provided.

--list-scopes::
  Shows all scopes in the bucket.

--create-collection <collection>::
  Makes the collection in the scope. The option takes a path in dot
  format (scope.collection), specifying the scope in which the
  collection and the name to be created.

--edit-collection <collection>::
  Edits the collection in the scope. The option takes a path in dot
  format (scope.collection), specifying the collection in a scope which is
  to be edited.

--drop-collection <collection>::
  Removes the collection from the scope. The option takes a path in
  dot format (scope.collection), specifying the scope from which
  the collection and collection-name are to be removed.

--list-collections [<scope_list>]::
  Takes an optional comma separated list of scope names. It will show all the
  collections inside those scopes. If no scopes are provided it will show all the
  collections.

--max-ttl <seconds>::
  Specifies the maximum TTL (time-to-live) for all documents in the
  collection, in seconds. If enabled and a document is mutated with
  no TTL or a TTL greater than than the maximum, its TTL will be set
  to the maximum TTL. Setting this option to 0 disables the use of
  max-TTL, and the largest TTL that is allowed is 2147483647. This setting
  cannot be edited after a collection has been created.

--enable-history-retention <0|1>::
  Specifies whether or not the document history retention should be enabled for
  the collection. To enable the document history retention, set this option to
  "1". To disable the document history retention, set this option to "0".
  This setting can be edited after a collection has been created.


include::{partialsdir}/cbcli/part-host-formats.adoc[]

include::{partialsdir}/cbcli/part-certificate-authentication.adoc[]

== EXAMPLES

To create a new scope called "chairs" in the furniture bucket.

  $ couchbase-cli collection-manage -c 192.168.1.5 -u Administrator \
   -p password --bucket furniture --create-scope chairs

To create a new collection called "couches" in the chairs scope in the
furniture bucket.

  $ couchbase-cli collection-manage -c 192.168.1.5 -u Administrator \
   -p password --bucket furniture --create-collection chairs.couches

To edit the collection called "couches" in the chairs scope in the furniture
bucket.

  $ couchbase-cli collection-manage -c 192.168.1.5 -u Administrator \
   -p password --bucket furniture --edit-collection chairs.couches
   --enable-history-retention 1

To list all of the collections in the chairs and tables scopes in the furniture
bucket.

  $ couchbase-cli collection-manage -c 192.168.1.5 -u Administrator \
   -p password --bucket furniture --list-collections chairs,tables

To drop the couches collection from the chairs scope in the
furniture bucket.

  $ couchbase-cli collection-manage -c 192.168.1.5 -u Administrator \
   -p password --bucket furniture --drop-collection chairs.couches


To drop the chair scope from the furniture bucket

  $ couchbase-cli collection-manage -c 192.168.1.5 -u Administrator \
   -p password --bucket furniture --drop-scope chairs


== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

include::{partialsdir}/cbcli/part-footer.adoc[]
