= couchbase-cli-ip-family(1)
:description: Edits cluster IP family settings
ifndef::doctype-manpage[:doctitle: ip-family]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-ip-family -
endif::[]
Edits cluster IP family settings

== SYNOPSIS

[verse]
_couchbase-cli ip-family_ [--cluster <url>] [-username <username>] [--password <password>]
    [--client-cert <path>] [--client-cert-password <password>] [--client-key <path>]
    [--client-key-password <password>] [--get] [--set] [--ipv4] [--ipv4only] [--ipv6]
    [--ipv6only]

== DESCRIPTION

This command changes the IP family used for inter-cluster communication.
To do this it will execute a number of instructions in each node in the
cluster. The clusters names must be FQDN and not IP addresses. It also
provides an option to retrieve the current IP family being used.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--get::
  Show current IP family.

--set::
  Change the cluster IP family, specify the IP family to be used using the
  --ipv4 or --ipv6 flags.

--ipv4::
  When specified together with --set it will change the cluster to use IPv4 for
  communication between the nodes. It will still be possible for traffic to go
  over IPv6 from clients.

--ipv4only::
  When specified together with --set it will change the cluster to only use IPv4.
  It will not blind to any IPv6 addresses, all traffic will be over IPv4

--ipv6::
  When specified together with --set it will change the cluster to use IPv6 for
  communication between the nodes. It will still be possible for traffic to go
  over IPv4 from clients.

--ipv6only::
  When specified together with --set it will change the cluster to only use IPv6.
  It will not blind to any IPv4 addresses, all traffic will be over IPv6.

include::{partialsdir}/cbcli/part-host-formats.adoc[]

include::{partialsdir}/cbcli/part-certificate-authentication.adoc[]

== EXAMPLES

For a cluster with nodes [`cb1.com`, `cb2.com`, `cb3.com`] communicating via IPv4 we
can change the IP family being used to IPv6 by using the following command.
----
$ couchbase-cli ip-family -c http://cb1.com:8091 -u Administrator \
  -p password --set --ipv6
----
This command will configure each node in the cluster to use IPv6. To check what
family is being used use the command below:
----
$ couchbase-cli ip-family -c http://cb1.com:8091 -u Administrator \
  -p password --get
----

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-setting-security[1]
man:couchbase-cli-ssl-manage[1]
man:couchbase-cli-node-to-node-encryption[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
