= couchbase-cli-collect-logs-status(1)
:description: Get log collection status
ifndef::doctype-manpage[:doctitle: collect-logs-status]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-collect-logs-status -
endif::[]
Get log collection status

== SYNOPSIS

[verse]
_couchbase-cli collect-logs-status_ [--cluster <url>] [--username <user>]
    [--password <password>]

== DESCRIPTION

This command is used to check the status of the log collection task that is
either currently running or last completed. This command is especially useful
since it lists the exact location of the collected files on each node. Upon a
successful run of this command the output will either be one of the two messages
below.

  No log collection tasks were found

or

  Status: <running | cancelled | completed>
  Details:
    Node: <node name>
    Status: <started | collected>
    path: <path to the location of the collected logs>

If logs for multiple nodes were collected, then multiple nodes will be listed in
the details section.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

To see the status of a running or completed log collection task run the command
below.

  $ couchbase-cli collect-logs-status -c 192.168.1.5 --username Administrator \
   --password password

  Status: completed
  Details:
    Node: n_0@192.168.1.5
    Status: collected
    path: /opt/couchbase/var/lib/couchbase/tmp/collectinfo-2016-09-27T005502-n_0@192.168.1.5.zip

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-collect-logs-start[1],
man:couchbase-cli-collect-logs-stop[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
