= couchbase-cli-master-password(1)
ifndef::doctype-manpage[:doctitle: master-password]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-master-password -
endif::[]
Sends the Couchbase master password

== SYNOPSIS

[verse]
_couchbase-cli master-password_ [--new-password <password>]

== DESCRIPTION

Couchbase Server Enterprise Edition has a "Secret Management" feature, which
allows users to securely encrypt passwords and other sensitive configuration
information that is stored on disk. These secrets must be stored in a secure
way, and access must be controlled to reduce the risk of accidental exposure.
By using Secret Management in Couchbase Server, secrets are written to disk
in encrypted format. To decrypt these secrets, Couchbase requires the
entering of  a "master password", which is supplied by the user during server
startup. This master password can be passed to the server using this command.

By default the Secret Management feature is disabled. To enable the feature,
you must first set the master password. Once a master password is set, the
user is required to enter it when the server starts up. This can be done by
setting the environment variable CB_MASTER_PASSWORD=<password> during server
startup. Alternatively, you can enter the master password using the
couchbase-cli `master-password` command. This command must be run locally on
the node that needs to be unlocked and the user running the command must be
a member of the `couchbase` group (or be root.)

== OPTIONS


--send-password::
  Sends the master password to the server that is waiting to start up.


== EXAMPLES

To use the Secret Management feature, the first thing you need to do is set a
password on each node of the cluster. To do this, install and start Couchbase,
but don't go through the setup process or initialize the cluster. Once
Couchbase has started, run the following command to set the master password
for your server.

  $ couchbase-cli setting-master-password -c 127.0.0.1 -u Administrator \
    -p password --new-password password

This will cause Couchbase Server to wait for the master password before
starting up. When your cluster is restarted, you will notice that the server
doesn’t fully come up as it is now waiting for the master password to be
entered. You can do this by running the command below. The master-password
subcommand has to be run locally on the node that is waiting for the master
password and as the user must have be able to read files in the `couchbase`
group.

  $ couchbase-cli master-password --send-password password

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-setting-master-password[1],
man:couchbase-cli-cluster-init[1],
man:couchbase-cli-server-add[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
