= couchbase-cli-host-list(1)
:description: Lists all hosts in the cluster
ifndef::doctype-manpage[:doctitle: host-list]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-host-list -
endif::[]
Lists all hosts in the cluster

== SYNOPSIS

[verse]
_couchbase-cli host-list_ [--cluster <url>] [--username <user>]
    [--password <password>]

== DESCRIPTION

Displays a list of hostnames corresponding to each node in the cluster. Each
hostname is printed to stdout on its own line. The hostname may or may not
contain a port number. If the port number is not a part of the hostname, then
the port number is assumed to be 8091.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

To get a list of hostnames for each node in the cluster run the following
command:

  $ couchbase-cli host-list -c 192.168.1.5:8091 --username Administrator \
   --password password

   cb1.mydomain.com:8091
   cb2.mydomain.com:8091
   cb3.mydomain.com:8091

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-server-info[1],
man:couchbase-cli-server-list[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
