= couchbase-cli-backup-service(1)
ifndef::doctype-manpage[:doctitle: backup-service]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-backup-service -
endif::[]
Manages the Couchbase backup service

== SYNOPSIS

[verse]
_couchbase-cli backup-service_ [--cluster <url>] [--username <user>] [--password <password>]
    [--client-cert <path>] [--client-cert-password <password>] [--client-key <path>]
    [--client-key-password <password>] <settings|instance|profile>

== DESCRIPTION

Manage the backup service

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

== SUBCOMMANDS

man:couchbase-cli-backup-service-settings[1]::
  Manage backup service configuration.

man:couchbase-cli-backup-service-repository[1]::
  Manage backup repositories.

man:couchbase-cli-backup-service-plan[1]::
  Manage backup plans.

man:couchbase-cli-backup-service-nodes-threads-map[1]::
  Manage the backup service nodes threads map.

man:couchbase-cli-backup-service-repo-list[1]::
  List backup service repositories.

man:couchbase-cli-backup-service-repo-get[1]::
  Retrieve a backup service repository.

include::{partialsdir}/cbcli/part-host-formats.adoc[]

include::{partialsdir}/cbcli/part-certificate-authentication.adoc[]

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

include::{partialsdir}/cbcli/part-footer.adoc[]
