= couchbase-cli-setting-query(1)
:description: Manage query engine settings
ifndef::doctype-manpage[:doctitle: setting-query]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-setting-query -
endif::[]
Manage query engine settings

== SYNOPSIS

[verse]
_couchbase-cli setting-query [--cluster <url>] [--username <user>]
    [--password <password>] [--get] [--set] [--pipeline-batch <num>]
    [--pipeline-cap <num>] [--scan-cap <size>] [--timeout <ms>]
    [--prepared-limit <max>] [--completed-limit <max>]
    [--log-level <trace|debug|info|warn|error|server|none>]
    [--max-parallelism <max>] [--n1ql-feature-control <num>]
    [--temp-dir <path>] [--temp-dir-size <mebibytes>]
    [--curl-access <restricted|unrestricted>]
    [--allowed-urls <urls>] [--disallowed-urls <urls>]

== DESCRIPTION

Manage query service settings

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--get::
  Retrieve current query service settings.

--set::
  Set query engine settings.

--pipeline-batch <num>::
  Number of items execution operators can batch, the default is 16.

--pipeline-cap <num>::
  Maximum number of items each execution operator can buffer, the default 512.

--scan-cap <size>::
  Maximum buffer size for index scans; use zero or negative value to disable.
  The default 512.

--timeout <ms>::
  Server execution timeout; use zero or negative value to disable. By default
  is unlimited.

--prepared-limit <max>::
  Maximum number of prepared statements, the default is 16384.

--completed-limit <max>::
  Maximum number of completed requests, the default is 4000.

--completed-threshold <ms>::
  Cache completed queries lasting longer than this threshold (in milliseconds),
  the default is 1000.

--log-level <trace|debug|info|warn|error|server|none>::
  Query engine log level, the default level is info.

--max-parallelism <max>::
  Maximum parallelism per query; use zero or negative value to disable.
  The default is 1.

--n1ql-feature-control <num>::
  N1QL Feature Controls.
  0x0001 (1) Disable Index Aggregation

--temp-dir <path>::
  Specify the directory for temporary query data.

--temp-dir-size <mebibytes>::
  Maximum size in mebibytes for the temporary query data directory.

== QUERY CURL ACCESS OPTIONS

--curl-access <restricted|unrestricted>::
  Specify either unrestricted or restricted, to determine which URLs are permitted
  to be accessed by the curl function.

--allowed-urls <urls>::
  Comma separated lists of URLs that are allowed to be accessed by the curl
  function. This option must be provided together with --curl-access restricted.
  If disallowed-urls also provided then the disallowed list takes precedence.

--disallowed-urls <urls>::
  Comma separated lists of URLs that are disallowed to be accessed by the curl
  function. This option must be provided together with --curl-access restricted.
  If allowed-urls also provided then the disallowed list takes precedence.

include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

To retrieve the query settings:

  $ couchbase-cli setting-query -c 127.0.01:8091 -u Administrator \
   -p password --get

To set any of the query settings for example maximum parallelism and log level:

  $ couchbase-cli setting-query -c 127.0.01:8091 -u Administrator \
   -p password --set --log-level debug --max-parallelism 4

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
