= couchbase-cli-eventing-function-setup(1)
ifndef::doctype-manpage[:doctitle: eventing-function-setup]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-eventing-function-setup -
endif::[]
Manage Events

== SYNOPSIS

[verse]
_couchbase-cli eventing-function-setup_ [--cluster <url>] [--username <user>]
    [--password <password>]  [--import] [--export] [--export-all]
    [--delete] [--list] [--deploy] [--undeploy] [--boundary <from-everything|from-now>]
    [--pause] [--resume] [--name <name>] [--file <file>]

== DESCRIPTION

This command is used to manage functions in the Event service

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--import::
  Import function(s) from a file. This option requires --file to be
  specified. The file provided should be from the --export option.

--export::
  Export a named function to a file. This option requires --file and
  --name to be specified.

--export-all::
  Export all functions to a file. This option requires --file to be
  specified.

--delete::
  Deletes a named function. Functions can only be deleted when in the
  undeployed state. This option requires --name to be specified.

--list::
  List all functions.

--deploy::
  Deploys the named function. This option requires --name to be specified.

--undeploy::
  Undeploys the named function. This option requires --name to be specified.

--pause::
  Pause the named function. This option requires --name to be specified. See
  the PAUSE VS UNDEPLOY section for more information.

--resume::
  Resume the named function. This option requires --name to be specified. See
  the PAUSE VS UNDEPLOY section for more information.

--name <name>::
  The name of the function to take a action against. This is used by
  --export, --delete, --deploy and --undeploy options only.

--boundary <from-everything|from-now>::
  The place to start at when deploying a new function. Accepts 'from-now' or
  'from-everything' defaulting to 'from-everything' if the --boundary flag
  is omitted.

--file <file>::
  The file to import and export functions to. This is used by --export and
  --import options only.


include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

To import functions from a file called _functions.json_:

  $ couchbase-cli eventing-function-setup -c 192.168.1.5 -u Administrator \
   -p password --import --file functions.json

To export a function called _alert_function_ to a file called
_functions.json_:

  $ couchbase-cli eventing-function-setup -c 192.168.1.5 -u Administrator \
   -p password --export --name alert_function --file functions.json

To export all functions to a file called _functions.json_:

  $ couchbase-cli eventing-function-setup -c 192.168.1.5 -u Administrator \
   -p password --export-all --file functions.json

To list all functions:

  $ couchbase-cli eventing-function-setup -c 192.168.1.5 -u Administrator \
   -p password --list

To delete a function called _alert_function_:

  $ couchbase-cli eventing-function-setup -c 192.168.1.5 -u Administrator \
   -p password --delete --name alert_function

To deploy a function called _alert_function_ and process both all historical data and
new data:

  $ couchbase-cli eventing-function-setup -c 192.168.1.5 -u Administrator \
   -p password --deploy --name alert_function --boundary from-everything

To deploy a function called _alert_function_ and process only new data:

  $ couchbase-cli eventing-function-setup -c 192.168.1.5 -u Administrator \
   -p password --deploy --name alert_function --boundary from-now

To undeploy a function called _alert_function_:

  $ couchbase-cli eventing-function-setup -c 192.168.1.5 -u Administrator \
   -p password --undeploy --name alert_function

To pause a function called _alert_function_:

    $ couchbase-cli eventing-function-setup -c 192.168.1.5 -u Administrator \
     -p password --pause --name alert_function

To resume a function called _alert_function_:

    $ couchbase-cli eventing-function-setup -c 192.168.1.5 -u Administrator \
     -p password --resume --name alert_function

== UNDEPLOY VS PAUSE
Once you undeploy an eventing function you will have no opportunity to resume
from the point at which the function was undeployed; this is not the case for
pause/resume. Pausing an eventing function allows you to make changes to it
or its settings while retaining the ability to continue from the point at
which the function was paused.

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

include::{partialsdir}/cbcli/part-footer.adoc[]
