= couchbase-cli-setting-password-policy(1)
ifndef::doctype-manpage[:doctitle: setting-password-policy]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-setting-password-policy -
endif::[]
Manage the password policy for new users

== SYNOPSIS

[verse]
_couchbase-cli setting-password-policy_ [--cluster <url>] [--username <user>]
    [--password <password>] [--get] [--set] [--min-length <num>]
    [--uppercase <0|1> ] [--lowercase <0|1>] [--digits <0|1>]
    [--special-chars <0|1>]

== DESCRIPTION

Allows retrieval of the current password policy and creating a new password
policy for new Couchbase users. This allows administrators to customize the
complexity of user passwords.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--get::
  Retrieves the current password policy.

--set::
  Creates a new password policy. Use the flags below to specify different
  levels of password complexity required for new users and users who change
  their existing passwords.

--min-length <num>::
  Specifies the minimum password length for new passwords.

--uppercase <0|1>::
  Specifies that new passwords must contain at least one upper case letter.

--lowercase <0|1>::
  Specifies that new passwords must contain at least one lower case letter.

--digit <0|1>::
  Specifies that new passwords must contain at least one digit.

--special-char <0|1>::
  Specifies that new passwords must contain at least one special character.

include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

To get the current password policy run the following command.

  $ couchbase-cli setting-password-policy -c 192.168.1.5 -u Administrator \
   -p password --get

To set a new password policy where the minimum password length is 10 character
and require that all passwords contain an upper case letter, lower case letter,
and a digit run the following command.

  $ couchbase-cli setting-password-policy -c 192.168.1.5 -u Administrator \
   -p password --set --min-length 10 --uppercase 1 --lowercase 1 --digits 1

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli[1],
man:couchbase-cli-user-manage[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
