= couchbase-cli-setting-notification(1)
:description: Modifies notification settings
ifndef::doctype-manpage[:doctitle: setting-notification]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-setting-notification -
endif::[]
Modifies notification settings

== SYNOPSIS

[verse]
_couchbase-cli setting-notification_ [--cluster <url>] [--username <user>]
    [--password <password>] [--enable-notifications <int>]

== DESCRIPTION

Enabling notifications allows the Couchbase Administration Console to notify
users about newer versions of Couchbase Server. This system also collects
information about use and experience with the product every time an
administrator interacts with the administrator user interface. It collects
configuration, usage and performance data, including cluster information
(such as settings and configuration, software version, cluster ID, load
levels, and resource quotas), and browser and network information (such as
IP address, inferred geolocation only at the city level, and browser type).
This does not allow Couchbase to track your specific interactions or usage
of the Couchbase Server. It never accesses or collects any data stored
within Couchbase Server.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--enable-notification <int>::
  Specifies whether or not notifications should be enabled. To enable
  notifications set this flag to "1". To disable notifications set this flag
  to "0".

include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

To enable notifications on a Couchbase cluster run the following command\&.

  $ couchbase-cli setting-notifications -c 192.168.1.5 -u Administrator \
   -p password --enable-notification 1

To disable notifications run the following command.

  $ couchbase-cli setting-notifications -c 192.168.1.5 -u Administrator \
   -p password --enable-notification 0

== DISCUSSION

The setting-notification subcommand either enables or disables notifications
about new Couchbase releases. This setting is a global parameter and applies to
all nodes in a cluster.

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli[1],
man:couchbase-cli-cluster-init[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
