= couchbase-cli-setting-saslauthd(1)
ifndef::doctype-manpage[:doctitle: setting-saslauthd]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-setting-saslauthd -
endif::[]
Modifies saslauthd settings

== SYNOPSIS

[verse]
_couchbase-cli setting-saslauthd_ [--cluster <url>] [--username <user>]
    [--password <password>] [--admins <admins_list>]
    [--roadmins <ro_admin_list>] [--default <default>]
    [--enabled <1|0>]

== DESCRIPTION

This command is only available for clusters running Enterprise Edition on
GNU/Linux.

This command allows users to enable SASL on their cluster as well as add
administrator and read-only administrator SASL users to their cluster.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--admins <admins_list>::
  A list of SASL users who should have administrator privileges on this
  cluster. This list should be comma separated if multiple users are being
  added.

--roadmins <ro_admin_list>::
  A list of SASL users who should have read-only administrator privileges on
  this cluster. This list should be comma separated if multiple users are
  being added.

--enabled <1|0>::
  Enables or disables SASL on this cluster. To enable SASL set this option to
  "1". To disable SASL set this parameter to "0".

--default <default>::
  Specifies the default role for SASL users who have not been explicitly been
  added to the cluster. This option may be set to "admins", "ro_admins", or
  "none". If this option is set to "admins" then all SASL users not explicitly
  add to this cluster have administrator privileges. If this option is set to
  "roadmins" then all SASL users not explicitly add to this cluster have
  read-only administrator privileges. If this option is set to "none" then all
  SASL users not explicitly add to this cluster will have no access. This
  option default to "none".

include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

To enable SASL on a cluster run the following command.
----
$ couchbase-cli setting-saslauthd -c 192.168.1.5 --username Administrator \
 --password password --enabled 1
----
To add users `alice` and `barry` as Administrators and users `clair` and `daniel` as
Read-Only Administrators run the following command.
----
$ couchbase-cli setting-saslauthd -c 192.168.1.5 --username Administrator \
 --password password --enabled 1 --admins alice,barry \
 --roadmins clair,daniel
----
To enable SASL and allow all SASL users to have Administrator access run the
following command.
----
$ couchbase-cli setting-saslauthd -c 192.168.1.5 --username Administrator \
 --password password --enabled 1 --default admins
----
== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-admin-role-manage[1],
man:couchbase-cli-user-manage[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
