= couchbase-cli-setting-cluster(1)
:description: Modifies cluster settings
ifndef::doctype-manpage[:doctitle: setting-cluster]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-setting-cluster -
endif::[]
Modifies cluster settings

== SYNOPSIS

[verse]
_couchbase-cli setting-cluster_ [--cluster <url>] [--username <user>]
    [--password <password>] [--cluster-username <username>]
    [--cluster-password <password>] [--cluster-port <port>]
    [--cluster-ramsize <mebibytes>] [--cluster-name <name>]
    [--cluster-index-ramsize <mebibytes>] [--cluster-fts-ramsize <mebibytes>]
    [--cluster-eventing-ramsize <mebibytes>]
    [--cluster-analytics-ramsize <mebibytes>]

== DESCRIPTION

This command is used to modify cluster level settings. It allows users to change
the Couchbase root username and password, change the port that the cluster
manager listens on, and modify the data, index, full-text or analytics service
memory quotas.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--cluster-username::
  Specifies the new username for the Couchbase administrator user.

--cluster-password::
  Specifies the new password for the Couchbase administrator user.

--cluster-ramsize::
  Specifies the data services memory quota. This quota will be assigned to all
  future nodes added to the cluster with the data service.

--cluster-fts-ramsize::
  Sets the full-text service memory quota. This parameter is required if the
  full-text service is specified in the --services option. This quota will be
  assigned to all future nodes added to the cluster with the full-text
  service.

--cluster-index-ramsize::
  Sets the index service memory quota. This parameter is required if the index
  service is specified in the --services option. This quota will be assigned
  to all future nodes added to the cluster with the index service.

--cluster-eventing-ramsize::
  Sets the Eventing service memory quota (in MiB). This parameter is required
  if the Eventing service is specified in the --services option. This quota
  will be assigned to all future nodes added to the cluster with the eventing
  service.

--cluster-analytics-ramsize::
  Sets the Analytics service memory quota (in MiB). This parameter is required
  if the Analytics service is specified in the --services option. This quota
  will be assigned to all future nodes added to the cluster with the
  Analytics service.

--cluster-name::
  Sets the name for this cluster. Naming clusters is useful when you have
  multiple Couchbase clusters in your deployment.

--cluster-port::
  Specifies the port for the Couchbase Administration Console. Defaults to
  port 8091.

include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

To change the username and password of the Couchbase administrator user run the
following command.

  $ couchbase-cli setting-cluster -c 192.168.1.5:8091 --username cur_user \
   --password cur_password --cluster-username new_username \
   --cluster-password new_password

To change the port number that the cluster manager listens on and the cluster
name to "new_name" run the following command.

  $ couchbase-cli setting-cluster -c 192.168.1.5:8091 --username Administrator \
   --password password --cluster-port 5000 --cluster-name new_name

To change the memory quota of the data server to 2048 and the memory quota of
the index service to 4096 run the following command.

  $ couchbase-cli setting-cluster -c 192.168.1.5:8091 --username Administrator \
   --password password --cluster-ramsize 2048 --cluster-index-ramsize 4096

All of the parameters in this command can be specified at the same time. To
change the username and password of the Couchbase administrator user, change the
port number to 5000, change the cluster name to "new_name", change the memory
quota of the data service to 2048 and change the memory quota of the index
service to 4096 run the following command.

  $ couchbase-cli setting-cluster -c 192.168.1.5:8091 --username cur_user \
   --password cur_password --cluster-username new_username \
   --cluster-password new_password --cluster-port 5000 \
   --cluster-name new_name --cluster-ramsize 2048 --cluster-index-ramsize 4096

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-cluster-init[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
