= couchbase-cli-node-init(1)
ifndef::doctype-manpage[:doctitle: node-init]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-node-init -
endif::[]
Initializes a node

== SYNOPSIS

[verse]
_couchbase-cli node-init_ [--cluster <url>] [--username <user>]
    [--password <password>] [--node-init-data-path <path>]
    [--node-init-index-path <path>] [--node-init-analytics-path <path>]
    [--node-init-eventing-path <path>] [--node-init-hostname <hostname>]
    [--node-init-java-home <path>] [--ipv4] [--ipv6]

== DESCRIPTION

This command initializes a Couchbase Server node. In particular this command
allows the user to set the data path, index path, analytics path, java home
and hostname. These settings must be set prior to initializing the cluster or
adding the node to an existing cluster as they cannot be changed later. The
hostname however can be changed later if the node is the only node in the
cluster.

To get the best performance from Couchbase Server, it is recommended that the
data, index and analytics paths be set to separate disks.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--node-init-data-path::
  The path to store data files create by the Couchbase data service. Note that
  this path is also where view indexes are written on this server. This flag
  can only be specified against a node that is not yet part of a cluster.

--node-init-index-path::
  The path to store files create by the Couchbase index service. This flag can
  only be specified against a node that is not yet part of a cluster. Multiple
  paths can be specified by setting this option multiple times.

--node-init-analytics-path::
  The path to store files create by the Couchbase Analytics service. This flag
  can only be specified against a node that is not yet part of a cluster.

--node-init-eventing-path::
  The path to store files create by the Couchbase Eventing service. This flag
  can only be specified against a node that is not yet part of a cluster.

--node-init-hostname::
  Specifies the hostname for this server.

--node-init-java-home::
  Specifies the location of the Java Runtime Environment for the Analytics
  service to use.

--ipv4::
  Switch the node to use ipv4 for node to node communication

--ipv6::
  Switch the node to use ipv6 for node to node communication

include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

To initialize a node and set the index path to /mnt1/indexes and the data path
to /mnt2/data run the following command. Note that this command must be run
before the node becomes part of a cluster.

  $ couchbase-cli node-init -c 192.168.1.5 \
   --node-init-data-path /mnt2/data --node-init-index-path /mnt1/indexes

In the command above, the cluster username and password have not yet been set so
you can skip adding these to the command line. If you later initialize the cluster
and want to set the hostname for the cluster, then run the command
below. Note that this time the cluster is initialized, so you must include the
username and password.

  $ couchbase-cli node-init -c 192.168.1.5 -u Administrator -p password \
   --node-init-hostname cb1.mydomain.com

You could have alternatively set all five of these options below before
initializing the cluster. This can be done with the following command.

  $ couchbase-cli node-init -c 192.168.1.5 --node-init-hostname cb1.mydomain.com \
   --node-init-data-path /mnt2/data --node-init-index-path /mnt1/indexes \
   --node-init-analytics-path /mnt3/analytics \
   --node-init-java-home /usr/lib/java/

Again, note that you don't need the username and password because in this example
the cluster has not yet been initialized.

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-cluster-init[1],
man:couchbase-cli-server-add[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
