= couchbase-cli-setting-xdcr(1)
ifndef::doctype-manpage[:doctitle: setting-xdcr]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-setting-xdcr -
endif::[]
Modifies cross data center replication (XDCR) settings

== SYNOPSIS

[verse]
_couchbase-cli setting-xdcr_ [--cluster <url>] [--username <user>]
    [--password <password>] [--checkpoint-interval <seconds>]
    [--worker-batch-size <num>] [--doc-batch-size <kilobytes>]
    [--failure-restart-interval <seconds>] [--source-nozzle-per-node <num>]
    [--target-nozzle-per-node <num>] [--bandwidth-usage-limit <num>]
    [--enable-compression <num>] [--stats-interval <milliseconds>]
    [--optimistic-replication-threshold <bytes>] [--log-level <level>]

== DESCRIPTION

This command sets global default settings for all XDCR replications. If you only
want to change the settings for a single XDCR replication see the
man:couchbase-cli-xdcr-replicate[1] command.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--checkpoint-interval <seconds>::
  The interval between checkpoints in seconds. The value of this option must
  be between 60 and 14,400.

--worker-batch-size <num>::
  The worker batch size. The value of this option must be between 500 and
  10,000.

--doc-batch-size <kilobytes>::
  The document batch size in Kilobytes. The value of this option must be
  between 10 and 100,000.

--failure-restart-interval <seconds>::
  Interval for restarting failed XDCR connections in seconds. The value of
  this option must be between 1 and 300.

--optimistic-replication-threshold <bytes>::
  Document body size threshold in bytes used to trigger optimistic
  replication.

--source-nozzle-per-node <num>::
  The number of source nozzles to each node in the target cluster. The
  value of this option must be between 1 and 10.

--target-nozzle-per-node <num>::
  The number of outgoing nozzles to each node in the target cluster. The
  value of this option must be between 1 and 10.

--bandwidth-usage-limit <num>::
  The default bandwidth limit for XDCR replications in Megabytes per second.

--enable-compression <num>::
  Specifies whether or not XDCR compression is enabled. Set this option to
  "1" to enable compression or "0" to disable compression. This feature is
  only available in Couchbase Enterprise Edition and can only be used where
  the target cluster supports compression.

--log-level <level>::
  The XDCR log level.

--stats-interval <milliseconds>::
  The interval for statistics updates in milliseconds.

include::{partialsdir}/cbcli/part-host-formats.adoc[]

== EXAMPLES

If we want to change the checkpoint interval to 500 seconds, the worker batch to
1000 documents, the document batch size to 10240KB, the failure restart interval
to 60 seconds. the optimistic replication threshold to 102400 bytes, the source
nozzles to 8, the target nozzles to 8, the log level to info, and the stats
interval to 100 milliseconds run the following command.

  $ couchbase-cli setting-xdcr -c 192.168.1.5 -u Administrator \
   -p password --checkpoint-interval 500 --worker-batch-size 1000 \
   --doc-batch-size 10000 --failure-restart-interval 60 \
   --optimistic-replication-threshold 102400 --source-nozzle-per-node 8 \
   --target-nozzle-per-node 8 --log-level Info --stats-interval 1000
   
== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-xdcr-replicate[1],
man:couchbase-cli-xdcr-setup[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
