= couchbase-cli-reset-cipher-suites(1)
:description: Resets the Couchbase Server cipher suites to the default
ifndef::doctype-manpage[:doctitle: reset-cipher-suites]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-reset-cipher-suites -
endif::[]
Resets the Couchbase Server cipher suites to the default

== SYNOPSIS

[verse]
_couchbase-cli reset-cipher-suites_ [--force] [--port <port>]

== DESCRIPTION

This command is used to reset the cipher suites to the default for Couchbase
Server. This command should only be used when the cipher have been configured
in a way that breaks remote access. The cipher suit can be managed using the
man:couchbase-cli-setting-security[1] command.

The `reset-cipher-suites` command must be run locally on a node that is part
of the cluster (i.e. must connect to the node the command is run on). This is
required, as the cluster and ciphers suits could be configured in a way
that disables remote access. `reset-cipher-suites` uses the local
authentication token as a result the user that execute the command needs to
have read access to the local Couchbase Server configuration files.

== OPTIONS

--force::
  It reset the cipher suites without asking for confirmation.

--port::
  Specify the REST API port of the locally running Couchbase Server. If no
  port is specified the default port 8091 is used.

== EXAMPLES

To reset the cipher suites to the default:

  $ couchbase-cli reset-cipher-suites


== SEE ALSO

man:couchbase-cli-setting-security[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
