= couchbase-cli-setting-enterprise-analytics(1)
:description: Manage Enterprise Analytics service settings
ifndef::doctype-manpage[:doctitle: setting-enterprise-analytics]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-setting-enterprise-analytics -
endif::[]
Manage Enterprise Analytics service settings

== SYNOPSIS

[verse]
_couchbase-cli setting-enterprise-analytics_ [--get] [--set] [--replicas <num>]

== DESCRIPTION

Manage Enterprise Analytics service settings

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--get::
  Retrieve current Enterprise Analytics service settings.

--set::
  Set Enterprise Analytics settings.

--partitions <num>::
  The number of storage partitions (positive integer, lower than the configured maximum)

--scheme <scheme>::
  The BLOB storage scheme (e.g. s3)

--bucket <bucket>::
  The BLOB storage bucket

--prefix <prefix>::
  The BLOB storage prefix

--region <region>::
  The BLOB storage region

--endpoint <endpoint>::
  The BLOB storage endpoint

--anonymous-auth <0|1>::
  Allow BLOB storage anonymous auth

--path-style-addressing <0|1>::
  Use BLOB storage path style addressing

include::{partialsdir}/cbcli/part-host-formats.adoc[]

include::{partialsdir}/cbcli/part-certificate-authentication.adoc[]

== EXAMPLES

To retrieve the Enterprise Analytics service settings:

  $ couchbase-cli setting-enterprise-analytics -c 127.0.01:8091 -u Administrator \
   -p password --get

To set the BLOB storage scheme to s3:

  $ couchbase-cli setting-enterprise-analytics -c 127.0.01:8091 -u Administrator \
   -p password --set --scheme s3

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
