= couchbase-cli-setting-security(1)
:description: Manage security policies
ifndef::doctype-manpage[:doctitle: setting-security]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-setting-security -
endif::[]
Manage security policies

== SYNOPSIS

[verse]
_couchbase-cli setting-security_ [--cluster <url>] [--username <user>] [--password <password>]
    [--client-cert <path>] [--client-cert-password <password>] [--client-key <path>]
    [--client-key-password <password>] [--set] [--get] [--disable-http-ui <0|1>]
    [--disable-www-authenticate <0|1>]
    [--cluster-encryption-level <all|control|strict>]
    [--tls-min-version <tlsv1.2|tlsv1.3>]
    [--tls-honor-cipher-order <0|1>] [---cipher-suites <ciphers>]
    [--hsts-max-age <seconds] [--hsts-preload-enabled <0|1>]
    [--hsts-include-sub-domains-enabled <0|1>]

== DESCRIPTION

This command allows configuring cluster wide security settings.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--get::
  Gets current security settings.

--set::
  Set new security settings.

--disable-http-ui <0|1>::
  Specifies whether the Couchbase Web Console can be accessible
  over http. To disable access set this option to "1". To enable access
  set this option to "0". By default, access to the UI over http is
  enabled. Notice that this will only disable http access to the endpoints
  that are used by the Web UI and not all endpoints that use the http port
  (e.g. setting this option to "1" will disable access to the `http://<addr>:8091`
  endpoint but will not disable access to the `http://<addr>:8091/logs` endpoint
  since it is used by the REST API and not Web UI). If your goal is to disable
  non-local http access completely, you should use the `--cluster-encryption-level`
  flag and set its value to "strict".

--disable-www-authenticate <0|1>::
  Specifies whether Couchbase Server will respond with WWW-Authenticate to
  unauthenticated requests. By default this is enabled which may result
  in browsers prompting the user for username/password and then caching
  the information.

--cluster-encryption-level <all|control|strict>::
  Specifies the cluster encryption level. The level is used when cluster
  encryption is turned on. If the level is "all" then both data
  and control messages between the nodes in the cluster will be sent over
  encrypted connections. If the level is "control" only control messages will
  be sent encrypted. If the level is "strict" it is the same as having the
  level "all" but all non-TLS ports on non-loopback interfaces will be closed.
  By default when cluster encryption is turned on, the level will be "control".
  Before setting the level to "strict" you will need to perform a number of
  important actions, see
  https://docs.couchbase.com/server/current/manage/manage-security/manage-tls.html#enforcing-tls[Enforcing TLS].

--tls-min-version <tlsv1.2|tlsv1.3>::
  Specify the minimum TLS protocol version to be used across all of the
  Couchbase services.

--tls-honor-cipher-order <1|0>::
  Specifies whether the cipher-order must be followed across all of the
  services. When set to 1, this allows weaker ciphers to be included in the
  cipher list for backwards compatibility of older clients/browsers while still
  forcing the newer clients to use stronger ciphers.

--cipher-suites <cipher>::
  Specify the cipher suite to be used across all of the couchbase services.
  The ciphers have to be a comma separated list such as:
  `TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA`.
  If an empty string is given ("") then the cipher list will be reset to its default.

--hsts-max-age <seconds>::
  Specifies the max-ages directive in seconds the server uses in the Strict-Transport-Security
  header.

--hsts-preload-enabled <1|0>::
  Specifies whether the preload directive for the Strict-Transport-Security header the server uses
  should be set.

--hsts-include-sub-domains-enabled <1|0>::
  Specifies whether the includeSubDomains directive for the Strict-Transport-Security header the
  server uses should be set.

include::{partialsdir}/cbcli/part-host-formats.adoc[]

include::{partialsdir}/cbcli/part-certificate-authentication.adoc[]

== EXAMPLES

To disable the Couchbase Administration Console over HTTP run the following
command.

  $ couchbase-cli setting-security -c localhost -u Administrator \
   -p password --set --disable-http-ui 1

To change the encryption level to "all" run the following command.

  $ couchbase-cli setting-security -c localhost -u Administrator \
   -p password --set --cluster-encryption-level all

To change max-ages directive for Strict-Transport-Security header to 10 seconds.

  $ couchbase-cli setting-security -c localhost -u Administrator \
   -p password --set --hsts-max-age 10

== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli[1]
man:couchbase-cli-node-to-node-encryption[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
