= couchbase-cli-setting-ldap(1)
ifndef::doctype-manpage[:doctitle: setting-ldap]

ifdef::doctype-manpage[]
== NAME

couchbase-cli-setting-ldap -
endif::[]
Configure LDAP

== SYNOPSIS
[verse]
_couchbase-cli setting-ldap_ [--cluster <url>] [--username <user>]
    [--password <password>] [--authentication-enabled <1|0>]
    [--authorization-enabled <1|0>] [--hosts <host_list>] [--port <port>]
    [--encryption <tls|startTLS|none>] [--disable-cert-validation]
    [--ca-cert <path>] [--user-dn-mapping <mapping>][--request-timeout <ms>]
    [--max-parallel <max>] [--max-cache-size <size>]
    [--cache-value-lifetime <ms>] [--query-dn <dn>] [--query-pass <pass>]
    [--group-query <query>] [--enable-nested-groups <0|1>]
    [--nested-group-max-depth <depth>]


== DESCRIPTION

This command allows administrators to configure and connect LDAP servers.

== OPTIONS

include::{partialsdir}/cbcli/part-common-options.adoc[]

--authentication-enabled <1|0>::
  Enables using LDAP to authenticate users

--authorization-enabled <1|0>::
  Enables using LDAP to give users authorization

--host <host_list>::
  Specifies a comma separated list of LDAP hosts.

--port <port>::
  LDAP port.

--encryption <tls|startTLS|none>::
  Security used to communicate with LDAP servers. Supported options
  [tls, startTLS, none].

--disable-cert-validation::
  Disable server certificate validation.

--ca-cert <path>::
  CA certificate to be used for server's certificate validation, required if
  certificate validation is not disabled

--request-timeout <ms>::
  The timeout for LDAP requests in milliseconds.

--user-dn-mapping <mapping>::
  User to DN mapping, if not specified username is used as user's DN.

--max-parallel-connections <max>::
  Maximum number of parallel connections that can be established with LDAP
  servers.

--max-cache-size <size>::
  Maximum number of requests that can be cached, defaults to 10000.

--cache-value-lifetime <ms>::
  Lifetime of values in cache in milliseconds. Default 300000 ms.

--query-dn <dn>::
  DN for groups synchronization

--query-pass <pass>::
  Password for groups synchronization

--group-query <query>::
  LDAP query to get users' group by username. RFC4516 format, like
  '%D?memberOf?base'. This option works the following way: if attribute is
  present in the query the list of attributes in the query result is considered
  as list of user’s groups (single entry result is expected). %u and %D
  placeholders could be used.
  %u - username,
  %D - user’s DN.
  If attribute is not present in the query every returned entry is considered
  as a group;

--nested-groups-enabled <0|1>::
  If enabled Couchbase server will try to recursively search for groups for
  every discovered ldap group.

--nested-groups-max-depth <depth>::
  Maximum number of recursive groups requests the server is allowed to perform.
  This option is only valid when nested groups are enabled. The depth is an
  integer between 1 and 100, default is 10.


== ENVIRONMENT AND CONFIGURATION VARIABLES

include::{partialsdir}/cbcli/part-common-env.adoc[]

== SEE ALSO

man:couchbase-cli-user-manage[1]

include::{partialsdir}/cbcli/part-footer.adoc[]
