#!/usr/bin/env python
# -*-python-*-

"""
Backup tool for Couchbase.
"""

import pump_transfer
import sys

if __name__ == '__main__':
    pump_transfer.exit_handler(pump_transfer.Backup().main(sys.argv))