#!/usr/bin/env python3
# -*-python-*-

"""
Restore tool for Couchbase.
"""

import sys

import pump_transfer

if __name__ == '__main__':
    pump_transfer.exit_handler(pump_transfer.Restore().main(sys.argv))
