#!/usr/bin/env python
# -*-python-*-

"""
Data transfer tool for Couchbase.
"""

try:
    import pump_sfd
except ImportError:
    print "warning: could not import couchstore module" \
        "; accessing local couchstore-files:// will not work" \
        "; please check your PYTHONPATH and LD_LIBRARY_PATH"

import pump_transfer
import sys
import os

if __name__ == '__main__':
    if os.name == 'nt':
        mydir = os.path.dirname(sys.argv[0])
        bin_dir = os.path.join(mydir, '..')
        path = [mydir, bin_dir, os.environ['PATH']]
        os.environ['PATH'] = ';'.join(path)
    sys.exit(pump_transfer.Transfer().main(sys.argv))
