#!/usr/bin/env python
# -*-python-*-

"""
Data transfer tool for Couchbase.
"""

import os
import platform
import sys

try:
    import pump_sfd
except ImportError:
    if platform.system() == "Windows":
        p = "PATH"
    else:
        p = "LD_LIBRARY_PATH"
    print ("warning: could not import couchstore module"
           "; accessing local couchstore-files:// will not work"
           "; please check your PYTHONPATH and %s environment variables" % (p))

import pump_transfer

if __name__ == '__main__':
    if platform.system() == 'Windows':
        mydir = os.path.dirname(sys.argv[0])
        bin_dir = os.path.join(mydir, '..')
        path = [mydir, bin_dir, os.environ['PATH']]
        os.environ['PATH'] = ';'.join(path)
    sys.exit(pump_transfer.Transfer().main(sys.argv))
