#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
couchbase-cli - command-line cluster administration tool
"""

import cbmgr
import sys

def main():
    try:
        cli = cbmgr.CouchbaseCLI()
        args = cli.parse(sys.argv)
        cli.execute(args)
    except KeyboardInterrupt:
        sys.exit(1)

if __name__ == '__main__':
    main()
