#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
couchbase-cli - command-line cluster administration tool
"""

import cbmgr as cbcli

import getopt
import sys
import os

import node
import xdcr
import util_cli as util
import usage
from timeout import TimeoutException

CB_USERNAME = 'CB_REST_USERNAME'
CB_PASSWORD = 'CB_REST_PASSWORD'

class StubCommand():
    """A temoporary stub class to maintain functionality during command refactoring"""

    def __init__(self):
        pass

    def runCmd():
        raise NotImplementedError

    def getCommandSummary(self, cmd):
        """Return one-line summary info for each supported command"""
        command_summary = {
            "admin-role-manage" : "set access-control roles for users",
            "cluster-edit" : "modify cluster settings",
            "cluster-init" : "set the username,password and port of the cluster",
            "bucket-list" : "list all buckets in a cluster",
            "bucket-create" : "add a new bucket to the cluster",
            "bucket-edit" : "modify an existing bucket",
            "bucket-delete" : "delete an existing bucket",
            "bucket-flush" : "flush all data from disk for a given bucket",
            "bucket-compact" : "compact database and index data",
            "collect-logs-start" : "start a cluster-wide log collection",
            "collect-logs-status" : "show the status of cluster-wide log collection",
            "collect-logs-stop" : "stop a cluster-wide log collection",
            "failover": "failover one or more servers",
            "group-manage" :"manage server groups",
            "host-list" : "list all hosts in a cluster",
            "node-init" : "set node specific parameters",
            "rebalance": "start a cluster rebalancing",
            "rebalance-status": "show status of current cluster rebalancing",
            "rebalance-stop": "stop current cluster rebalancing",
            "recovery" :"recover one or more servers",
            "server-add": "add one or more servers to the cluster",
            "server-info" : "show details on one server",
            "server-list" : "list all servers in a cluster",
            "server-readd" :"readd a server that was failed over",
            "setting-cluster" : "set cluster settings",
            "setting-compaction" : "set auto compaction settings",
            "setting-alert" : "set email alert settings",
            "setting-audit": "set audit settings",
            "setting-autofailover": "set auto failover settings",
            "setting-index" : "set index settings",
            "setting-notification" : "set notification settings",
            "setting-ldap" : "set ldap settings",
            "user-manage" : "manage read only user",}
        if cmd in command_summary:
            return command_summary[cmd]

        return None


def main():

    debug = False

    (cluster, user, password, ssl) = ('', '', '', False)

    try:
        (opts, _args) = getopt.getopt(sys.argv[2:],
                                     'a:b:c:dse:gdlmo:OPp:r:Ssu:vVhH', [
                'cluster=',
                'debug',
                'storage',
                'password=',
                'user=',
                'mem',
                'output=',
                'os',
                'ports',
                'stats',
                'license',
                'server-add=',
                'server-add-username=',
                'server-add-password=',
                'server-remove=',
                'server-failover=',
                'server-recovery=',
                'cluster-init=',
                'cluster-init-username=',
                'cluster-username=',
                'cluster-init-password=',
                'cluster-password=',
                'cluster-init-port=',
                'cluster-port=',
                'cluster-init-ramsize=',
                'cluster-ramsize=',
                'cluster-name=',
                'cluster-index-ramsize=',
                'cluster-fts-ramsize=',
                'index-storage-setting=',
                'enable-auto-failover=',
                'auto-failover-timeout=',
                'enable-notification=',
                'enable-email-alert=',
                'compaction-db-percentage=',
                'compaction-db-size=',
                'compaction-view-percentage=',
                'compaction-view-size=',
                'compaction-period-from=',
                'compaction-period-to=',
                'enable-compaction-abort=',
                'enable-compaction-parallel=',
                'metadata-purge-interval=',
                'node-init=',
                'node-init-data-path=',
                'node-init-index-path=',
                'node-init-hostname=',
                'bucket=',
                'bucket-type=',
                'bucket-port=',
                'bucket-password=',
                'bucket-ramsize=',
                'bucket-replica=',
                'bucket-priority=',
                'bucket-eviction-policy=',
                'enable-flush=',
                'enable-index-replica=',
                'wait',
                'force',
                'data-only',
                'view-only',
                'version',
                'xdcr-cluster-name=',
                'xdcr-hostname=',
                'xdcr-username=',
                'xdcr-password=',
                'xdcr-from-bucket=',
                'xdcr-to-bucket=',
                'xdcr-replicator=',
                'xdcr-replication-mode=',
                'xdcr-demand-encryption=',
                'xdcr-certificate=',
                'create',
                'edit',
                'delete',
                'list',
                'set',
                'pause',
                'resume',
                'settings',
                'ro-username=',
                'ro-password=',
                'checkpoint-interval=',
                'worker-batch-size='
                'doc-batch-size=',
                'failure-restart-interval=',
                'optimistic-replication-threshold=',
                'source-nozzle-per-node=',
                'target-nozzle-per-node=',
                'log-level=',
                'stats-interval=',
                'email-recipients=',
                'email-sender=',
                'email-user=',
                'email-password=',
                'email-host=',
                'email-port=',
                'enable-email-encrypt=',
                'alert-auto-failover-node',
                'alert-auto-failover-max-reached',
                'alert-auto-failover-node-down',
                'alert-auto-failover-cluster-small',
                'alert-auto-failover-disabled',
                'alert-ip-changed',
                'alert-disk-space',
                'alert-meta-overhead',
                'alert-meta-oom',
                'alert-write-failed',
                'alert-audit-msg-dropped',
                'group-name=',
                'rename=',
                'add-servers=',
                'move-servers=',
                'from-group=',
                'to-group=',
                'regenerate-cert=',
                'cluster-cert-info',
                'node-cert-info',
                'upload-cluster-ca=',
                'set-node-certificate',
                'extended',
                'recovery-type=',
                'recovery-buckets=',
                'nodes=',
                'all-nodes',
                'upload',
                'upload-host=',
                'customer=',
                'ticket=',
                'services=',
                'help',
                'ssl',
                'filter-expression=',
                'audit-enabled=',
                'audit-log-path=',
                'audit-log-rotate-interval=',
                'ldap-enabled=',
                'ldap-admins=',
                'ldap-roadmins=',
                'ldap-default=',
                'index-max-rollback-points=',
                'index-stable-snapshot-interval=',
                'index-memory-snapshot-interval=',
                'index-threads=',
                'index-log-level=',
                'vm=',
                'get-roles',
                'roles=',
                'my-roles',
                'set-users=',
                'set-names=',
                'delete-users=',
                'erl-path='
                ])
    except getopt.GetoptError, err:
        usage.command_error(err)
    if len(_args) > 0:
        err_message = ("Possible missing '--' in front of one of parameters '%s'," +
                       " please see -h for more help.") % _args
        usage.command_error(err_message)
    commands = {
        'host-list'         : StubCommand,
        'server-list'       : StubCommand,
        'server-info'       : StubCommand,
        'server-eshell'     : StubCommand,
        'server-add'        : StubCommand,
        'server-readd'      : StubCommand,
        'group-manage'      : StubCommand,
        'rebalance'         : StubCommand,
        'rebalance-stop'    : StubCommand,
        'rebalance-status'  : StubCommand,
        'failover'          : StubCommand,
        'recovery'          : StubCommand,
        'cluster-init'      : StubCommand,
        'cluster-edit'      : StubCommand,
        'ssl-manage'        : node.Node,
        'node-init'         : StubCommand,
        'user-manage'       : StubCommand,
        'collect-logs-start'  : StubCommand,
        'collect-logs-stop'   : StubCommand,
        'collect-logs-status' : StubCommand,
        'bucket-list'       : StubCommand,
        'bucket-create'     : StubCommand,
        'bucket-edit'       : StubCommand,
        'bucket-delete'     : StubCommand,
        'bucket-flush'      : StubCommand,
        'bucket-compact'    : StubCommand,
        'setting-cluster'   : StubCommand,
        'setting-compaction'    : StubCommand,
        'setting-notification'  : StubCommand,
        'setting-autofailover'  : StubCommand,
        'setting-alert'         : StubCommand,
        'setting-audit'         : StubCommand,
        'setting-ldap'          : StubCommand,
        'admin-role-manage'     : StubCommand,
        'setting-xdcr'          : xdcr.XDCR,
        'setting-index'         : StubCommand,
        'xdcr-setup'            : xdcr.XDCR,
        'xdcr-replicate'        : xdcr.XDCR,
        'help'                  : usage.Usage
        }

    if len(sys.argv) <= 1:
        usage.short_usage(commands)

    cmd = sys.argv[1]

    try:
        if cbcli.parse_command():
            return
    except KeyboardInterrupt:
        sys.exit(1)

    if cmd not in commands:
        # cmd not a command, maybe help is needed.
        for x in sys.argv:
            if x in ('-h', '-H', '--help'):
                usage.all_help(commands) # exits program.

        err_message = ("'%s' is not a couchbase-cli command;" +
                       " please see -h for more help.") % cmd
        usage.command_error(err_message) # exits program.

    if cmd == "help":
        usage.all_help(commands)

    # If a command and -h,-H,--help give context sensitive help by passing cmd
    for x in sys.argv:
        if x in ('-h', '-H', '--help'):
            usage.one_command_usage(cmd, commands)

    for (opt, arg) in opts:
        if opt in ('-c', '--cluster'):
            cluster = arg
        if opt in ('-u', '--user'):
            user = arg
        if opt in ('-p', '--password'):
            password = arg
        if opt in ('-d', '--debug'):
            debug = True
        if opt in ('-s', '--ssl'):
            ssl = True

    if cmd == "cluster-init" and not cluster:
        cluster = "127.0.0.1:8091"

    if not cluster:
        usage.command_error("please provide a CLUSTER, or use -h for more help.")

    if cmd != "cluster-init":
        if not user:
            if CB_USERNAME in os.environ:
                user = os.environ[CB_USERNAME]
            else:
                usage.command_error("Username cannot be empty. \
Please use -u or set environment variable %s."  % CB_USERNAME)
        if not password:
            if CB_PASSWORD in os.environ:
                password = os.environ[CB_PASSWORD]
            else:
                usage.command_error("Password cannot be empty. \
Please use -p or set environment variable %s." % CB_PASSWORD)

    server, port = util.hostport(cluster)

    if debug:
        print "INFO: running command: %s" % cmd

    c = commands[cmd]()
    try:
        c.runCmd(cmd, server, port, user, password, ssl, opts)
    except TimeoutException, err:
        print "TIMED OUT: command: %s: %s:%d, %s" % (cmd, server, port, err)
        sys.exit(1)
    except KeyboardInterrupt:
        print "INTERRUPTED: command: %s: %s:%d" % (cmd, server, port)
        sys.exit(1)
    except Exception, err:
        print "ERROR: command: %s: %s:%d, %s" % (cmd, server, port, err)
        sys.exit(1)

if __name__ == '__main__':
    main()
