#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
membase.py

This program is the top level source file for the Membase Command Line Tools
"""

import getopt
import sys
from listservers import *
from buckets import *
from node import *
from membase_info import *
from restclient import *

if __name__ == '__main__':
    (cluster, user, password) = ('', '', '')
    debug = False;
    try:
        (opts, args) = getopt.getopt(sys.argv[2:],
                                     'a:b:c:de:gdho:p:r:s', [
                'help',
                'cluster=',
                'debug',
                'password=',
                'user=',
                'output=',
                'stats',
                'server-add=',
                'server-add-username=',
                'server-add-password=',
                'server-remove=',
                'server-remove-username=',
                'server-remove-password=',
                ])
        cmd = sys.argv[1]
        if cmd in ('-h', '--help'):
            usage()
    except getopt.GetoptError, err:
        usage(err)

    # check if usage specified

    for (o, a) in opts:
        if o in ('-d', '--debug'):
            debug = True
        if o in ('-h', '--help'):
            cmd == 'help'
            usage()
        if o in ('-c', '--cluster'):
            cluster = a
        if o in ('-u', '--user'):
            user = a
        if o in ('-p', '--password'):
            password = a

    if not cluster and cmd != 'help':
        usage('You must specify at least two things: command, and cluster (--cluster)'
              )
    if not user:
        user = ''
    if not password:
        password = ''

    # these are the commands which map to the classes
    # the contain the implementation of that particular
    # command

    commands = {
        'server-list'       : Listservers,
        'bucket-list'       : Buckets,
        'bucket-details'    : Buckets,
        'bucket-stats'      : Buckets,
        'bucket-create'     : Buckets,
        'bucket-delete'     : Buckets,
        'bucket-flush'      : Buckets,
        'server-add'        : Node,
        'rebalance'         : Node,
        'rebalance-stop'    : Node,
        'rebalance-status'  : Node,
        'eject-server'      : Node,
        'failover'          : Node,
        }

    # make sure the command is defined

    if cmd not in commands:
        err_message = "command: '%s' not found" % cmd
        usage(err_message)

    # instantiate

    taskrunner = commands[cmd]()

    # call runCmd method

    taskrunner.runCmd(cmd, cluster, user, password, opts)
